'use client'

import { useReducer, useEffect, useCallback, useMemo } from 'react'
import { useRouter } from 'next/navigation'
import { toast } from 'sonner'
import {
  getOnboardingManagers,
  getOnboardingExistingModules,
  getOnboardingExistingProjects,
  getOnboardingProjectModules,
  validateOnboarding,
  createCustomerOnboarding,
  addClientUsersToExistingProject,
} from '@/app/actions/onboarding'
import { generateSecurePassword } from '@/lib/password-utils'
import type { OnboardingFormData, OnboardingResult, ClientUserType, ContractType, HypercareDuration } from '@/lib/types'

// ── Types ───────────────────────────────────────────────────────────────

export interface UserOption { id: string; name: string; email: string }
export interface ModuleOption { id: number; moduleName: string; projectId: number }
export interface ExistingProjectOption {
  id: number
  projectName: string
  projectCode: string
  clientId: string
  clientName: string | null
  clientEmail: string | null
}
export interface FormErrors { [key: string]: string }

export type WizardStep = 1 | 2 | 3 | 4 | 'review' | 'success'

export type OnboardingMode = 'new' | 'existing'

export interface ClientUserEntry {
  tempId: string
  firstName: string
  lastName: string
  email: string
  phoneNumber: string
  /** ISO-3166 alpha-2 country code for the phone number. */
  countryCode: string
  designation: string
  userType: ClientUserType
  password: string
  isAutoGenerated: boolean
  sendEmail: boolean
}

export interface OnboardingState {
  step: WizardStep
  mode: OnboardingMode
  submitting: boolean
  errors: FormErrors
  onboardingResult: OnboardingResult | null

  // Lookup data (loaded lazily per step)
  managerList: UserOption[]
  existingModules: ModuleOption[]
  availableProjects: ExistingProjectOption[]

  // Project
  projectName: string
  selectedManager: string
  selectedProjectId: number | null
  projectDescription: string
  projectStartDate: string
  projectEndDate: string
  projectType: string
  projectPriority: string
  projectNotes: string

  // Modules
  newModules: { name: string; description: string }[]
  selectedExistingModules: number[]
  moduleSearch: string
  // Existing project mode — project's modules + new modules to create
  projectModules: ModuleOption[]
  loadingProjectModules: boolean
  existingModeNewModules: { name: string; description: string }[]

  // Client Users (multiple)
  clientUsers: ClientUserEntry[]
  editingUserTempId: string | null  // null = adding new, non-null = editing existing

  // Form fields for the user being added/edited
  userFormFirstName: string
  userFormLastName: string
  userFormEmail: string
  userFormPhoneNumber: string
  userFormCountryCode: string
  userFormDesignation: string
  userFormUserType: ClientUserType
  userFormPassword: string
  userFormUseManualPassword: boolean
  userFormShowPassword: boolean
  userFormSendEmail: boolean

  // Support Contract
  contractType: ContractType | ''
  hypercareDuration: HypercareDuration | ''
  supportHours: string
  supportStartDate: string
  supportEndDate: string
  supportRemarks: string

  // Notification Preferences
  enableTeamsNotifications: boolean
}

type Action =
  | { type: 'SET_STEP'; step: WizardStep }
  | { type: 'SET_SUBMITTING'; submitting: boolean }
  | { type: 'SET_ERRORS'; errors: FormErrors }
  | { type: 'CLEAR_ERRORS' }
  | { type: 'SET_ONBOARDING_RESULT'; result: OnboardingResult | null }
  | { type: 'SET_MANAGERS'; managers: UserOption[] }
  | { type: 'SET_MODULES'; modules: ModuleOption[] }
  | { type: 'SET_EXISTING_PROJECTS'; projects: ExistingProjectOption[] }
  | { type: 'SET_FIELD'; field: string; value: any }
  | { type: 'SET_NEW_MODULES'; modules: { name: string; description: string }[] }
  | { type: 'SET_SELECTED_EXISTING_MODULES'; ids: number[] }
  | { type: 'ADD_MODULE' }
  | { type: 'REMOVE_MODULE'; index: number }
  | { type: 'UPDATE_MODULE'; index: number; field: string; value: string }
  | { type: 'TOGGLE_EXISTING_MODULE'; id: number }
  | { type: 'LOAD_DRAFT'; data: OnboardingFormData }
  // User management actions
  | { type: 'ADD_USER'; user: ClientUserEntry }
  | { type: 'REMOVE_USER'; tempId: string }
  | { type: 'UPDATE_USER'; tempId: string; user: ClientUserEntry }
  | { type: 'SET_EDITING_USER'; tempId: string | null }
  | { type: 'SET_USER_FORM_FIELD'; field: string; value: any }
  | { type: 'RESET_USER_FORM' }

function calculateHypercareEndDate(startDate: string, durationDays: number): string {
  if (!startDate || !durationDays) return ''
  const start = new Date(startDate)
  start.setDate(start.getDate() + durationDays)
  return start.toISOString().split('T')[0]
}

let tempIdCounter = 0
function generateTempId(): string {
  return `user_${++tempIdCounter}_${Date.now()}`
}

const emptyUserForm = {
  userFormFirstName: '',
  userFormLastName: '',
  userFormEmail: '',
  userFormPhoneNumber: '',
  userFormCountryCode: 'US',
  userFormDesignation: '',
  userFormUserType: 'standard' as ClientUserType,
  userFormPassword: '',
  userFormUseManualPassword: false,
  userFormShowPassword: false,
  userFormSendEmail: false,
}

const initialState: OnboardingState = {
  step: 1,
  mode: 'new',
  submitting: false,
  errors: {},
  onboardingResult: null,
  managerList: [],
  existingModules: [],
  availableProjects: [],
  projectName: '',
  selectedManager: '',
  selectedProjectId: null,
  projectDescription: '',
  projectStartDate: '',
  projectEndDate: '',
  projectType: '',
  projectPriority: '',
  projectNotes: '',
  newModules: [],
  selectedExistingModules: [],
  moduleSearch: '',
  // Existing project mode — project's modules + new modules to create
  projectModules: [],
  loadingProjectModules: false,
  existingModeNewModules: [],
  clientUsers: [],
  editingUserTempId: null,
  ...emptyUserForm,
  contractType: '',
  hypercareDuration: '',
  supportHours: '',
  supportStartDate: '',
  supportEndDate: '',
  supportRemarks: '',
  enableTeamsNotifications: false,
}

function onboardingReducer(state: OnboardingState, action: Action): OnboardingState {
  switch (action.type) {
    case 'SET_STEP':
      return { ...state, step: action.step }
    case 'SET_SUBMITTING':
      return { ...state, submitting: action.submitting }
    case 'SET_ERRORS':
      return { ...state, errors: action.errors }
    case 'CLEAR_ERRORS':
      return { ...state, errors: {} }
    case 'SET_ONBOARDING_RESULT':
      return { ...state, onboardingResult: action.result }
    case 'SET_MANAGERS':
      return { ...state, managerList: action.managers }
    case 'SET_MODULES':
      return { ...state, existingModules: action.modules }
    case 'SET_EXISTING_PROJECTS':
      return { ...state, availableProjects: action.projects }
    case 'SET_FIELD':
      return { ...state, [action.field]: action.value }
    case 'SET_NEW_MODULES':
      return { ...state, newModules: action.modules }
    case 'SET_SELECTED_EXISTING_MODULES':
      return { ...state, selectedExistingModules: action.ids }
    case 'ADD_MODULE':
      return { ...state, newModules: [...state.newModules, { name: '', description: '' }] }
    case 'REMOVE_MODULE':
      return { ...state, newModules: state.newModules.filter((_, j) => j !== action.index) }
    case 'UPDATE_MODULE': {
      const updated = [...state.newModules]
      updated[action.index] = { ...updated[action.index], [action.field]: action.value }
      return { ...state, newModules: updated }
    }
    case 'TOGGLE_EXISTING_MODULE': {
      const exists = state.selectedExistingModules.includes(action.id)
      return {
        ...state,
        selectedExistingModules: exists
          ? state.selectedExistingModules.filter((id) => id !== action.id)
          : [...state.selectedExistingModules, action.id],
      }
    }
    // ── User management ──────────────────────────────────────────────
    case 'ADD_USER':
      return {
        ...state,
        clientUsers: [...state.clientUsers, action.user],
        editingUserTempId: null,
        ...emptyUserForm,
        userFormPassword: '',
        userFormUseManualPassword: false,
      }
    case 'REMOVE_USER':
      return {
        ...state,
        clientUsers: state.clientUsers.filter((u) => u.tempId !== action.tempId),
        editingUserTempId: state.editingUserTempId === action.tempId ? null : state.editingUserTempId,
      }
    case 'UPDATE_USER':
      return {
        ...state,
        clientUsers: state.clientUsers.map((u) =>
          u.tempId === action.tempId ? action.user : u
        ),
        editingUserTempId: null,
        ...emptyUserForm,
        userFormPassword: '',
        userFormUseManualPassword: false,
      }
    case 'SET_EDITING_USER':
      return { ...state, editingUserTempId: action.tempId }
    case 'SET_USER_FORM_FIELD':
      return { ...state, [action.field]: action.value }
    case 'RESET_USER_FORM':
      return {
        ...state,
        editingUserTempId: null,
        ...emptyUserForm,
        userFormPassword: '',
        userFormUseManualPassword: false,
      }
    case 'LOAD_DRAFT': {
      const d = action.data
      // Backward compatibility: old drafts had 'clientUser' (single), new have 'clientUsers' (array)
      const clientUsers = Array.isArray(d.clientUsers) && d.clientUsers.length > 0
        ? d.clientUsers
        : (d as any).clientUser
          ? [(d as any).clientUser]
          : []
      return {
        ...state,
        projectName: d.project.projectName,
        selectedManager: d.project.managerId,
        projectDescription: d.project.description || '',
        projectStartDate: d.project.startDate || '',
        projectEndDate: d.project.endDate || '',
        projectType: d.project.projectType || '',
        projectPriority: d.project.priority || '',
        projectNotes: d.project.notes || '',
        newModules: d.modules.filter((m) => !m.isExisting).map((m) => ({ name: m.moduleName, description: m.description || '' })),
        selectedExistingModules: d.modules.filter((m) => m.isExisting && m.existingModuleId).map((m) => m.existingModuleId!),
        clientUsers: clientUsers.map((u: any) => ({
          tempId: generateTempId(),
          firstName: u.firstName || '',
          lastName: u.lastName || '',
          email: u.email || '',
          phoneNumber: u.phoneNumber || '',
          countryCode: u.countryCode || 'US',
          designation: u.designation || '',
          userType: u.userType || 'standard',
          password: u.password || '',
          isAutoGenerated: u.isAutoGenerated ?? true,
          sendEmail: u.sendEmail ?? false,
        })),
        contractType: (d.supportWallet as any).contractType || '',
        hypercareDuration: (d.supportWallet as any).hypercareDuration || '',
        supportHours: String(d.supportWallet.supportHours),
        supportStartDate: d.supportWallet.supportStartDate,
        supportEndDate: d.supportWallet.supportEndDate,
        supportRemarks: d.supportWallet.remarks || '',
        enableTeamsNotifications: (d as any).enableTeamsNotifications ?? false,
      }
    }
    default:
      return state
  }
}

export function useOnboarding(currentUserRole: string, currentUserId: string) {
  const router = useRouter()
  const [state, dispatch] = useReducer(onboardingReducer, initialState)

  // ── Lazy-load managers when user reaches Step 2 (Project) ─────────────
  useEffect(() => {
    if (state.step !== 2) return
    let cancelled = false
    async function loadManagers() {
      try {
        const [managers, projects] = await Promise.all([
          getOnboardingManagers(),
          getOnboardingExistingProjects(),
        ])
        if (!cancelled) {
          dispatch({ type: 'SET_MANAGERS', managers })
          dispatch({ type: 'SET_EXISTING_PROJECTS', projects })
          // Auto-assign if project_manager
          if (currentUserRole === 'project_manager') {
            dispatch({ type: 'SET_FIELD', field: 'selectedManager', value: currentUserId })
          }
        }
      } catch (err: any) {
        if (!cancelled) toast.error('Failed to load managers')
      }
    }
    loadManagers()
    return () => { cancelled = true }
  }, [state.step, currentUserRole, currentUserId])

  // ── Auto-generate password for user form ───────────────────────────
  useEffect(() => {
    if (!state.userFormUseManualPassword && !state.userFormPassword) {
      dispatch({ type: 'SET_USER_FORM_FIELD', field: 'userFormPassword', value: generateSecurePassword() })
    }
  }, [state.userFormUseManualPassword])

  // ── Auto-calculate hypercare end date ──────────────────────────────
  useEffect(() => {
    if (state.contractType === 'hypercare' && state.supportStartDate && state.hypercareDuration) {
      const endDate = calculateHypercareEndDate(state.supportStartDate, parseInt(String(state.hypercareDuration)))
      if (endDate !== state.supportEndDate) {
        dispatch({ type: 'SET_FIELD', field: 'supportEndDate', value: endDate })
      }
    }
  }, [state.contractType, state.supportStartDate, state.hypercareDuration])

  // ── Lazy-load existing modules when user reaches Step 3 (Modules) ────
  useEffect(() => {
    if (state.step !== 3) return
    let cancelled = false
    async function loadModules() {
      try {
        const modules = await getOnboardingExistingModules()
        if (!cancelled) dispatch({ type: 'SET_MODULES', modules })
      } catch (err: any) {
        if (!cancelled) toast.error('Failed to load existing modules')
      }
    }
    loadModules()
    return () => { cancelled = true }
  }, [state.step])

  // ── Load project modules when existing project is selected ───────────
  useEffect(() => {
    if (state.mode !== 'existing' || !state.selectedProjectId) return
    let cancelled = false
    async function loadProjectModules() {
      dispatch({ type: 'SET_FIELD', field: 'loadingProjectModules', value: true })
      try {
        const modules = await getOnboardingProjectModules(state.selectedProjectId!)
        if (!cancelled) {
          dispatch({ type: 'SET_FIELD', field: 'projectModules', value: modules })
        }
      } catch (err: any) {
        if (!cancelled) toast.error('Failed to load project modules')
      } finally {
        if (!cancelled) dispatch({ type: 'SET_FIELD', field: 'loadingProjectModules', value: false })
      }
    }
    loadProjectModules()
    // Reset new modules when project changes
    dispatch({ type: 'SET_FIELD', field: 'existingModeNewModules', value: [] })
    return () => { cancelled = true }
  }, [state.mode, state.selectedProjectId])

  // ── Convenience setters ─────────────────────────────────────────────
  const setField = useCallback((field: string, value: any) => {
    dispatch({ type: 'SET_FIELD', field, value })
  }, [])

  // ── User management ─────────────────────────────────────────────────
  const addUser = useCallback(() => {
    // Generate password on-the-fly if the auto-generation useEffect hasn't fired yet
    const password = state.userFormPassword || generateSecurePassword()
    const newUser: ClientUserEntry = {
      tempId: generateTempId(),
      firstName: state.userFormFirstName.trim(),
      lastName: state.userFormLastName.trim(),
      email: state.userFormEmail.trim(),
      phoneNumber: state.userFormPhoneNumber.trim(),
      countryCode: state.userFormCountryCode,
      designation: state.userFormDesignation.trim(),
      userType: state.userFormUserType,
      password,
      isAutoGenerated: !state.userFormUseManualPassword,
      sendEmail: state.userFormSendEmail,
    }
    dispatch({ type: 'ADD_USER', user: newUser })
  }, [state.userFormFirstName, state.userFormLastName, state.userFormEmail, state.userFormPhoneNumber,
      state.userFormCountryCode, state.userFormDesignation, state.userFormUserType,
      state.userFormPassword, state.userFormUseManualPassword, state.userFormSendEmail])

  const updateUser = useCallback(() => {
    if (!state.editingUserTempId) return
    const updatedUser: ClientUserEntry = {
      tempId: state.editingUserTempId,
      firstName: state.userFormFirstName.trim(),
      lastName: state.userFormLastName.trim(),
      email: state.userFormEmail.trim(),
      phoneNumber: state.userFormPhoneNumber.trim(),
      countryCode: state.userFormCountryCode,
      designation: state.userFormDesignation.trim(),
      userType: state.userFormUserType,
      password: state.userFormPassword,
      isAutoGenerated: !state.userFormUseManualPassword,
      sendEmail: state.userFormSendEmail,
    }
    dispatch({ type: 'UPDATE_USER', tempId: state.editingUserTempId, user: updatedUser })
  }, [state.editingUserTempId, state.userFormFirstName, state.userFormLastName, state.userFormEmail,
      state.userFormPhoneNumber, state.userFormCountryCode, state.userFormDesignation,
      state.userFormUserType, state.userFormPassword, state.userFormUseManualPassword,
      state.userFormSendEmail])

  const removeUser = useCallback((tempId: string) => {
    dispatch({ type: 'REMOVE_USER', tempId })
  }, [])

  const startEditingUser = useCallback((user: ClientUserEntry) => {
    dispatch({ type: 'SET_EDITING_USER', tempId: user.tempId })
    dispatch({ type: 'SET_USER_FORM_FIELD', field: 'userFormFirstName', value: user.firstName })
    dispatch({ type: 'SET_USER_FORM_FIELD', field: 'userFormLastName', value: user.lastName })
    dispatch({ type: 'SET_USER_FORM_FIELD', field: 'userFormEmail', value: user.email })
    dispatch({ type: 'SET_USER_FORM_FIELD', field: 'userFormPhoneNumber', value: user.phoneNumber })
    dispatch({ type: 'SET_USER_FORM_FIELD', field: 'userFormCountryCode', value: user.countryCode || 'US' })
    dispatch({ type: 'SET_USER_FORM_FIELD', field: 'userFormDesignation', value: user.designation })
    dispatch({ type: 'SET_USER_FORM_FIELD', field: 'userFormUserType', value: user.userType })
    dispatch({ type: 'SET_USER_FORM_FIELD', field: 'userFormPassword', value: user.password })
    dispatch({ type: 'SET_USER_FORM_FIELD', field: 'userFormUseManualPassword', value: !user.isAutoGenerated })
    dispatch({ type: 'SET_USER_FORM_FIELD', field: 'userFormShowPassword', value: false })
    dispatch({ type: 'SET_USER_FORM_FIELD', field: 'userFormSendEmail', value: user.sendEmail })
  }, [])

  const cancelEditing = useCallback(() => {
    dispatch({ type: 'RESET_USER_FORM' })
  }, [])

  const setUserFormField = useCallback((field: string, value: any) => {
    dispatch({ type: 'SET_USER_FORM_FIELD', field, value })
  }, [])

  // ── Validation ──────────────────────────────────────────────────────
  async function validateStep(s: WizardStep): Promise<boolean> {
    const errs: FormErrors = {}
    const st = state

    if (s === 1) {
      if (st.clientUsers.length === 0) {
        errs.clientUsers = 'At least one client user is required'
      } else {
        const emails = new Set<string>()

        for (let i = 0; i < st.clientUsers.length; i++) {
          const u = st.clientUsers[i]
          const idx = i + 1

          if (!u.firstName) errs[`user_${i}_firstName`] = `User #${idx}: First name is required`
          if (!u.lastName) errs[`user_${i}_lastName`] = `User #${idx}: Last name is required`

          if (!u.email) {
            errs[`user_${i}_email`] = `User #${idx}: Email is required`
          } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(u.email)) {
            errs[`user_${i}_email`] = `User #${idx}: Invalid email format`
          } else if (emails.has(u.email.toLowerCase())) {
            errs[`user_${i}_email`] = `User #${idx}: Duplicate email`
          } else {
            emails.add(u.email.toLowerCase())
            // Check against server for duplicate email (only if format is valid)
            try {
              const validationResult = await validateOnboarding('', u.email)
              if (validationResult.isDuplicateEmail) {
                errs[`user_${i}_email`] = `User #${idx}: A user with this email already exists`
              }
            } catch {
              // Silently handle validation errors
            }
          }

          if (!u.phoneNumber) errs[`user_${i}_phoneNumber`] = `User #${idx}: Phone number is required`

          if (u.password.length < 12) errs[`user_${i}_password`] = `User #${idx}: Password must be at least 12 characters`
        }
      }
    } else if (s === 2) {
      if (st.mode === 'new') {
        if (!st.projectName.trim()) errs.projectName = 'Project name is required'
        if (!st.selectedManager) errs.selectedManager = 'Project manager is required'
      } else {
        // Existing project mode
        if (!st.selectedProjectId) errs.selectedProjectId = 'Please select an existing project'
      }
    } else if (s === 3) {
      const total = st.newModules.length + st.selectedExistingModules.length
      if (total === 0) errs.modules = 'At least one module is required'
      const names = st.newModules.map((m) => m.name.trim().toLowerCase()).filter(Boolean)
      if (names.length !== new Set(names).size) errs.modules = 'Duplicate module names are not allowed'
    } else if (s === 4) {
      if (!st.contractType) errs.contractType = 'Contract type is required'
      if (st.contractType === 'hypercare' && !st.hypercareDuration) errs.hypercareDuration = 'Hypercare duration is required'
      if (st.contractType === 'support_agreement') {
        if (!st.supportHours || parseInt(st.supportHours) <= 0) errs.supportHours = 'Hours must be greater than zero'
        if (!st.supportEndDate) errs.supportEndDate = 'End date is required'
        if (st.supportStartDate && st.supportEndDate && new Date(st.supportEndDate) < new Date(st.supportStartDate)) {
          errs.supportEndDate = 'End date cannot be earlier than start date'
        }
      }
      if (st.contractType === 'hypercare' && st.supportStartDate && !st.supportEndDate) {
        errs.supportEndDate = 'End date is required'
      }
      if (!st.supportStartDate) errs.supportStartDate = 'Start date is required'
    }

    dispatch({ type: 'SET_ERRORS', errors: errs })
    return Object.keys(errs).length === 0
  }

  // ── Navigation ──────────────────────────────────────────────────────
  async function goNext() {
    // ── Step 1: Client Users ──────────────────────────────────────────
    // Handle separately with direct validation to avoid stale-state race conditions.
    if (state.step === 1) {
      // Auto-generate password if empty (handles race where useEffect hasn't fired yet)
      const password = state.userFormPassword || generateSecurePassword()

      if (state.clientUsers.length === 0) {
        // No users added — validate form fields directly, then add user automatically
        const errs: FormErrors = {}

        if (!state.userFormFirstName.trim()) errs.userFormFirstName = 'First name is required'
        if (!state.userFormLastName.trim()) errs.userFormLastName = 'Last name is required'

        if (!state.userFormEmail.trim()) {
          errs.userFormEmail = 'Email is required'
        } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(state.userFormEmail.trim())) {
          errs.userFormEmail = 'Invalid email format'
        }

        if (!state.userFormPhoneNumber.trim()) errs.userFormPhoneNumber = 'Phone number is required'
        if (password.length < 12) errs.userFormPassword = 'Password must be at least 12 characters'

        dispatch({ type: 'SET_ERRORS', errors: errs })

        if (Object.keys(errs).length > 0) {
          toast.error('Please fix the errors before continuing')
          return
        }

        // Check for duplicate email against the server
        try {
          const validationResult = await validateOnboarding('', state.userFormEmail.trim())
          if (validationResult.isDuplicateEmail) {
            dispatch({ type: 'SET_ERRORS', errors: { userFormEmail: 'A user with this email already exists' } })
            toast.error('Please fix the errors before continuing')
            return
          }
        } catch (e) {
          console.error('[Onboarding] Email validation error:', e)
          // Non-blocking: server will catch duplicates during submission
        }

        // Add user and navigate in one batch
        dispatch({ type: 'ADD_USER', user: {
          tempId: generateTempId(),
          firstName: state.userFormFirstName.trim(),
          lastName: state.userFormLastName.trim(),
          email: state.userFormEmail.trim(),
          phoneNumber: state.userFormPhoneNumber.trim(),
          countryCode: state.userFormCountryCode,
          designation: state.userFormDesignation.trim(),
          userType: state.userFormUserType,
          password,
          isAutoGenerated: !state.userFormUseManualPassword,
          sendEmail: state.userFormSendEmail,
        }})
      } else {
        // Users already exist — validate the existing user list
        if (!await validateStep(1)) {
          toast.error('Please fix the errors before continuing')
          return
        }
      }

      // Navigate to next step
      if (state.mode === 'existing') {
        dispatch({ type: 'SET_STEP', step: 'review' })
      } else {
        dispatch({ type: 'SET_STEP', step: 2 })
      }
      window.scrollTo({ top: 0, behavior: 'smooth' })
      return
    }

    // ── Steps 2, 3, 4: Standard validation via validateStep ───────────
    if (!await validateStep(state.step as WizardStep)) {
      toast.error('Please fix the errors before continuing')
      return
    }

    const s = state.step

    if (s === 4) {
      dispatch({ type: 'SET_STEP', step: 'review' })
    } else if (typeof s === 'number') {
      // For existing project mode: skip steps 3 (Modules) and 4 (Support)
      if (state.mode === 'existing' && s === 2) {
        dispatch({ type: 'SET_STEP', step: 'review' })
      } else {
        dispatch({ type: 'SET_STEP', step: (s + 1) as WizardStep })
      }
    }
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  function goPrev() {
    const s = state.step
    if (s === 'review') {
      // In existing project mode, go back to step 2
      if (state.mode === 'existing') {
        dispatch({ type: 'SET_STEP', step: 2 })
      } else {
        dispatch({ type: 'SET_STEP', step: 4 })
      }
    } else if (typeof s === 'number' && s > 1) {
      dispatch({ type: 'SET_STEP', step: (s - 1) as WizardStep })
    }
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  // ── Draft save / load ──────────────────────────────────────────────
  const saveDraft = useCallback(() => {
    const s = state
    const draft: OnboardingFormData = {
      project: {
        projectName: s.projectName, projectCode: '', clientId: '',
        managerId: s.selectedManager, description: s.projectDescription,
        startDate: s.projectStartDate, priority: s.projectPriority,
        projectType: s.projectType, notes: s.projectNotes,
      },
      modules: [
        ...s.newModules.map((m) => ({ moduleName: m.name, description: m.description })),
        ...s.existingModules
          .filter((em) => s.selectedExistingModules.includes(em.id))
          .map((em) => ({ moduleName: em.moduleName, isExisting: true, existingModuleId: em.id })),
      ],
      clientUsers: s.clientUsers.map((u) => ({
        firstName: u.firstName, lastName: u.lastName, email: u.email,
        phoneNumber: u.phoneNumber, countryCode: u.countryCode, designation: u.designation,
        userType: u.userType,
        password: u.password,
        isAutoGenerated: u.isAutoGenerated, sendEmail: u.sendEmail,
      })),
      enableTeamsNotifications: s.enableTeamsNotifications,
      supportWallet: {
        supportHours: parseInt(s.supportHours) || 0, supportStartDate: s.supportStartDate,
        supportEndDate: s.supportEndDate, remarks: s.supportRemarks,
        contractType: s.contractType as any,
        hypercareDuration: s.hypercareDuration ? parseInt(String(s.hypercareDuration)) as any : undefined,
      },
    }
    localStorage.setItem('onboardingDraft', JSON.stringify(draft))
    toast.success('Draft saved successfully')
  }, [state])

  const loadDraft = useCallback(() => {
    try {
      const raw = localStorage.getItem('onboardingDraft')
      if (!raw) { toast.error('No draft found'); return }
      const d: OnboardingFormData = JSON.parse(raw)
      dispatch({ type: 'LOAD_DRAFT', data: d })
      toast.success('Draft loaded successfully')
    } catch { toast.error('Failed to load draft') }
  }, [])

  // ── Submit Error Handling ──────────────────────────────────────────
  /**
   * Parse backend error messages and navigate to the correct step with field-level errors.
   * Maps server-side validation errors back to form fields so the user knows what to fix.
   */
  function handleSubmitError(message: string) {
    const s = state

    // ── User-level errors (Step 1) ────────────────────────────────────
    // Pattern: "User #N: <field description>" (no ^ anchor so it also matches
    // prefixed messages like "Failed to add client users. User #1: ...")
    const userErrorMatch = message.match(/User #(\d+): (.+)$/)
    if (userErrorMatch) {
      const userIndex = parseInt(userErrorMatch[1]) - 1
      const userDetail = userErrorMatch[2].toLowerCase()
      const user = s.clientUsers[userIndex]

      dispatch({ type: 'SET_STEP', step: 1 })

      if (user) {
        // Reuse existing startEditingUser to populate the editing form
        startEditingUser(user)

        // Highlight the specific field with the error
        const errs: FormErrors = {}
        if (userDetail.includes('email')) {
          errs.userFormEmail = userErrorMatch[2]
        } else if (userDetail.includes('first name')) {
          errs.userFormFirstName = userErrorMatch[2]
        } else if (userDetail.includes('last name')) {
          errs.userFormLastName = userErrorMatch[2]
        } else if (userDetail.includes('phone')) {
          errs.userFormPhoneNumber = userErrorMatch[2]
        } else if (userDetail.includes('password')) {
          errs.userFormPassword = userErrorMatch[2]
        } else {
          errs.clientUsers = message
        }
        dispatch({ type: 'SET_ERRORS', errors: errs })
      } else {
        dispatch({ type: 'SET_ERRORS', errors: { clientUsers: message } })
      }

      toast.error(message)
      window.scrollTo({ top: 0, behavior: 'smooth' })
      return
    }

    // Pattern: "The following email(s) already exist: email1, email2"
    const emailMatch = message.match(/The following email\(s\) already exist: (.+)/)
    if (emailMatch) {
      const duplicateEmails = emailMatch[1].split(', ').map((e: string) => e.trim().toLowerCase())
      dispatch({ type: 'SET_STEP', step: 1 })

      // Find the first user whose email matches a duplicate
      const affectedUser = s.clientUsers.find((u) => duplicateEmails.includes(u.email.toLowerCase()))
      if (affectedUser) {
        startEditingUser(affectedUser)
        dispatch({ type: 'SET_ERRORS', errors: { userFormEmail: `This email is already registered: ${affectedUser.email}` } })
      } else {
        dispatch({ type: 'SET_ERRORS', errors: { clientUsers: message } })
      }

      toast.error(message)
      window.scrollTo({ top: 0, behavior: 'smooth' })
      return
    }

    // ── Project-level errors (Step 2) ─────────────────────────────────
    if (
      message.toLowerCase().includes('project name') ||
      message.toLowerCase().includes('already exists')
    ) {
      dispatch({ type: 'SET_STEP', step: 2 })
      dispatch({ type: 'SET_ERRORS', errors: { projectName: message } })
      toast.error(message)
      window.scrollTo({ top: 0, behavior: 'smooth' })
      return
    }

    if (message.toLowerCase().includes('project manager')) {
      dispatch({ type: 'SET_STEP', step: 2 })
      dispatch({ type: 'SET_ERRORS', errors: { selectedManager: message } })
      toast.error(message)
      window.scrollTo({ top: 0, behavior: 'smooth' })
      return
    }

    // ── Module-level errors (Step 3) ──────────────────────────────────
    if (
      message.toLowerCase().includes('module') ||
      message.toLowerCase().includes('duplicate module')
    ) {
      dispatch({ type: 'SET_STEP', step: 3 })
      dispatch({ type: 'SET_ERRORS', errors: { modules: message } })
      toast.error(message)
      window.scrollTo({ top: 0, behavior: 'smooth' })
      return
    }

    // ── Support Contract errors (Step 4) ──────────────────────────────
    if (message.toLowerCase().includes('contract type')) {
      dispatch({ type: 'SET_STEP', step: 4 })
      dispatch({ type: 'SET_ERRORS', errors: { contractType: message } })
      toast.error(message)
      window.scrollTo({ top: 0, behavior: 'smooth' })
      return
    }

    if (message.toLowerCase().includes('hypercare duration')) {
      dispatch({ type: 'SET_STEP', step: 4 })
      dispatch({ type: 'SET_ERRORS', errors: { hypercareDuration: message } })
      toast.error(message)
      window.scrollTo({ top: 0, behavior: 'smooth' })
      return
    }

    if (message.toLowerCase().includes('support hours') || message.toLowerCase().includes('hours must be')) {
      dispatch({ type: 'SET_STEP', step: 4 })
      dispatch({ type: 'SET_ERRORS', errors: { supportHours: message } })
      toast.error(message)
      window.scrollTo({ top: 0, behavior: 'smooth' })
      return
    }

    if (
      message.toLowerCase().includes('support start date') ||
      message.toLowerCase().includes('start date')
    ) {
      dispatch({ type: 'SET_STEP', step: 4 })
      dispatch({ type: 'SET_ERRORS', errors: { supportStartDate: message } })
      toast.error(message)
      window.scrollTo({ top: 0, behavior: 'smooth' })
      return
    }

    if (
      message.toLowerCase().includes('support end date') ||
      message.toLowerCase().includes('end date')
    ) {
      dispatch({ type: 'SET_STEP', step: 4 })
      dispatch({ type: 'SET_ERRORS', errors: { supportEndDate: message } })
      toast.error(message)
      window.scrollTo({ top: 0, behavior: 'smooth' })
      return
    }

    // ── Client user count error ───────────────────────────────────────
    if (message.toLowerCase().includes('client user')) {
      dispatch({ type: 'SET_STEP', step: 1 })
      dispatch({ type: 'SET_ERRORS', errors: { clientUsers: message } })
      toast.error(message)
      window.scrollTo({ top: 0, behavior: 'smooth' })
      return
    }

    // ── Fallback: stay on current step, show the error in toast ───────
    toast.error(message)
  }

  // ── Submit ──────────────────────────────────────────────────────────
  async function handleFinish() {
    try {
      dispatch({ type: 'SET_SUBMITTING', submitting: true })
      const s = state

      if (s.mode === 'existing') {
        // ── Add users to existing project (with optional new modules) ─
        const newMods = s.existingModeNewModules
          .filter((m) => m.name.trim())
          .map((m) => ({ moduleName: m.name.trim(), description: m.description.trim() || undefined }))

        const result = await addClientUsersToExistingProject({
          projectId: s.selectedProjectId!,
          enableTeamsNotifications: s.enableTeamsNotifications,
          clientUsers: s.clientUsers.map((u) => ({
            firstName: u.firstName, lastName: u.lastName, email: u.email,
            phoneNumber: u.phoneNumber, countryCode: u.countryCode, designation: u.designation,
            userType: u.userType,
            password: u.password,
            isAutoGenerated: u.isAutoGenerated, sendEmail: u.sendEmail,
          })),
          ...(newMods.length > 0 ? { newModules: newMods } : {}),
        })
        if (result.success) {
          dispatch({ type: 'SET_ONBOARDING_RESULT', result })
          dispatch({ type: 'SET_STEP', step: 'success' })
          localStorage.removeItem('onboardingDraft')
          toast.success('Client users added successfully!')
        }
      } else {
        // ── Create new project (original flow) ──────────────────
        const formData: OnboardingFormData = {
          project: {
            projectName: s.projectName, projectCode: '', clientId: '',
            managerId: s.selectedManager, description: s.projectDescription,
            startDate: s.projectStartDate, priority: s.projectPriority,
            projectType: s.projectType, notes: s.projectNotes,
          },
          modules: [
            ...s.newModules.map((m) => ({ moduleName: m.name, description: m.description })),
            ...s.existingModules
              .filter((em) => s.selectedExistingModules.includes(em.id))
              .map((em) => ({ moduleName: em.moduleName, isExisting: true, existingModuleId: em.id })),
          ],
          clientUsers: s.clientUsers.map((u) => ({
            firstName: u.firstName, lastName: u.lastName, email: u.email,
            phoneNumber: u.phoneNumber, countryCode: u.countryCode, designation: u.designation,
            userType: u.userType,
            password: u.password,
            isAutoGenerated: u.isAutoGenerated, sendEmail: u.sendEmail,
          })),
          supportWallet: {
            supportHours: parseInt(s.supportHours) || 0,
            supportStartDate: s.supportStartDate,
            supportEndDate: s.contractType === 'hypercare'
              ? calculateHypercareEndDate(s.supportStartDate, s.hypercareDuration ? parseInt(String(s.hypercareDuration)) : 0)
              : s.supportEndDate,
            remarks: s.supportRemarks,
            contractType: s.contractType as any,
            hypercareDuration: s.hypercareDuration ? parseInt(String(s.hypercareDuration)) as any : undefined,
          },
        }
        const result = await createCustomerOnboarding(formData)
        if (result.success) {
          dispatch({ type: 'SET_ONBOARDING_RESULT', result })
          dispatch({ type: 'SET_STEP', step: 'success' })
          localStorage.removeItem('onboardingDraft')
          toast.success('Customer onboarded successfully!')
        }
      }
    } catch (err: any) {
      const message = err.message || 'Onboarding failed'
      handleSubmitError(message)
    } finally {
      dispatch({ type: 'SET_SUBMITTING', submitting: false })
    }
  }

  // ── Memoized helpers ────────────────────────────────────────────────
  const managerName = useMemo(
    () => state.managerList.find((m) => m.id === state.selectedManager)?.name || 'Unknown',
    [state.managerList, state.selectedManager]
  )

  const clientName = useMemo(
    () => state.clientUsers.length > 0
      ? `${state.clientUsers[0].firstName} ${state.clientUsers[0].lastName}`
      : 'Client (from step 1)',
    [state.clientUsers]
  )

  const selectedProjectName = useMemo(
    () => state.availableProjects.find((p) => p.id === state.selectedProjectId)?.projectName || 'Unknown',
    [state.availableProjects, state.selectedProjectId]
  )

  // Mode toggle
  const setMode = useCallback((mode: OnboardingMode) => {
    dispatch({ type: 'SET_FIELD', field: 'mode', value: mode })
  }, [])

  return {
    state,
    dispatch,
    setField,
    addModuleToExisting: useCallback(() => {
      dispatch({ type: 'SET_FIELD', field: 'existingModeNewModules', value: [...state.existingModeNewModules, { name: '', description: '' }] })
    }, [state.existingModeNewModules]),
    removeModuleFromExisting: useCallback((index: number) => {
      dispatch({ type: 'SET_FIELD', field: 'existingModeNewModules', value: state.existingModeNewModules.filter((_, i) => i !== index) })
    }, [state.existingModeNewModules]),
    updateModuleInExisting: useCallback((index: number, field: string, value: string) => {
      const updated = [...state.existingModeNewModules]
      updated[index] = { ...updated[index], [field]: value }
      dispatch({ type: 'SET_FIELD', field: 'existingModeNewModules', value: updated })
    }, [state.existingModeNewModules]),
    goNext,
    goPrev,
    saveDraft,
    loadDraft,
    handleFinish,
    router,
    managerName,
    clientName,
    selectedProjectName,
    setMode,
    // User management
    addUser,
    updateUser,
    removeUser,
    startEditingUser,
    cancelEditing,
    setUserFormField,
  }
}
