'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { Download, FileText, FileSpreadsheet, FileJson, FileType, Printer, Loader2, Check, ChevronDown } from 'lucide-react'

interface ReportExportProps {
  columns: { key: string; label: string; type?: string }[]
  data: Record<string, unknown>[]
  reportTitle: string
  summary: Record<string, string | number>
}

export function ReportExport({ columns, data, reportTitle, summary }: ReportExportProps) {
  const [exporting, setExporting] = useState<string | null>(null)
  const [exported, setExported] = useState<string | null>(null)

  async function handleExport(format: string) {
    setExporting(format)
    setExported(null)

    try {
      const filename = reportTitle.toLowerCase().replace(/\s+/g, '-')

      switch (format) {
        case 'csv': {
          const headers = columns.map(c => c.label)
          const rows = data.map(row => columns.map(c => String(row[c.key] ?? '')))
          const csv = [headers.join(','), ...rows.map(r => r.map(v => `"${v.replace(/"/g, '""')}"`).join(','))].join('\n')
          downloadFile(csv, `${filename}.csv`, 'text/csv')
          break
        }

        case 'json': {
          const json = JSON.stringify({ report: reportTitle, generatedAt: new Date().toISOString(), summary, data }, null, 2)
          downloadFile(json, `${filename}.json`, 'application/json')
          break
        }

        case 'txt': {
          const lines = [
            `=== ${reportTitle} ===`,
            `Generated: ${new Date().toLocaleString()}`,
            '',
            '=== Summary ===',
            ...Object.entries(summary).map(([k, v]) => `${k}: ${v}`),
            '',
            '=== Data ===',
            columns.map(c => c.label).join(' | '),
            ...data.slice(0, 100).map(row => columns.map(c => String(row[c.key] ?? '')).join(' | ')),
            '',
            `Total records: ${data.length}`,
          ]
          downloadFile(lines.join('\n'), `${filename}.txt`, 'text/plain')
          break
        }

        case 'xlsx': {
          const xml = `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
  <Worksheet ss:Name="Report">
    <Table>
      <Row><Cell><Data ss:Type="String">${reportTitle}</Data></Cell></Row>
      <Row><Cell><Data ss:Type="String">Generated: ${new Date().toLocaleString()}</Data></Cell></Row>
      <Row/>
      <Row>${columns.map(c => `<Cell><Data ss:Type="String">${c.label}</Data></Cell>`).join('')}</Row>
      ${data.slice(0, 1000).map(row => `<Row>${columns.map(c => `<Cell><Data ss:Type="String">${String(row[c.key] ?? '')}</Data></Cell>`).join('')}</Row>`).join('')}
    </Table>
  </Worksheet>
</Workbook>`
          downloadFile(xml, `${filename}.xlsx`, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
          break
        }

        case 'docx': {
          const html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>${reportTitle}</title>
<style>body{font-family:Calibri,sans-serif;max-width:800px;margin:0 auto;padding:2rem}
h1{font-size:1.5rem;color:#1e293b;border-bottom:2px solid #3B82F6;padding-bottom:0.5rem}
table{width:100%;border-collapse:collapse;margin:1rem 0}
th,td{padding:0.5rem;text-align:left;border-bottom:1px solid #e2e8f0;font-size:12px}
th{background:#f1f5f9;font-weight:600}
.footer{margin-top:2rem;font-size:0.75rem;color:#94a3b8;text-align:center}
.summary{display:flex;gap:1rem;flex-wrap:wrap;margin:1rem 0}
.summary-item{flex:1;min-width:120px;text-align:center;padding:0.75rem;background:#f8fafc;border-radius:0.5rem;border:1px solid #e2e8f0}
.summary-value{font-size:1.25rem;font-weight:700;color:#3B82F6}
.summary-label{font-size:0.7rem;color:#64748b;margin-top:0.25rem}
</style></head><body>
<h1>${reportTitle}</h1>
<p>Generated: ${new Date().toLocaleString()}</p>
<div class="summary">${Object.entries(summary).map(([k, v]) => `<div class="summary-item"><div class="summary-value">${v}</div><div class="summary-label">${k}</div></div>`).join('')}</div>
<table><tr>${columns.map(c => `<th>${c.label}</th>`).join('')}</tr>
${data.slice(0, 200).map(row => `<tr>${columns.map(c => `<td>${String(row[c.key] ?? '')}</td>`).join('')}</tr>`).join('')}
</table>
<div class="footer">${reportTitle} — Generated by Report Center</div>
</body></html>`
          downloadFile(html, `${filename}.docx`, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')
          break
        }

        case 'print': {
          const printWindow = window.open('', '_blank')
          if (!printWindow) return
          const printHtml = `<!DOCTYPE html>
<html><head><title>${reportTitle}</title>
<style>body{font-family:-apple-system,sans-serif;max-width:900px;margin:0 auto;padding:2rem;color:#1e293b}
h1{font-size:1.5rem;border-bottom:2px solid #3B82F6;padding-bottom:0.5rem}
table{width:100%;border-collapse:collapse;margin:1rem 0;font-size:12px}
th,td{padding:0.5rem 0.75rem;text-align:left;border-bottom:1px solid #e2e8f0}
th{background:#f1f5f9;font-weight:600}
.summary{display:flex;gap:1rem;flex-wrap:wrap;margin:1rem 0}
.summary-item{flex:1;min-width:120px;text-align:center;padding:0.75rem;background:#f8fafc;border-radius:0.5rem;border:1px solid #e2e8f0}
.summary-value{font-size:1.25rem;font-weight:700;color:#3B82F6}
.summary-label{font-size:0.7rem;color:#64748b}
.footer{margin-top:2rem;font-size:0.75rem;color:#94a3b8;text-align:center}
@media print{body{padding:0.5in} .no-print{display:none}}
</style></head><body>
<button class="no-print" onclick="window.print()" style="margin-bottom:1rem;padding:0.5rem 1rem;background:#111;color:white;border:none;border-radius:0.5rem;cursor:pointer">Print</button>
<h1>${reportTitle}</h1>
<p>Generated: ${new Date().toLocaleString()} | Records: ${data.length}</p>
<div class="summary">${Object.entries(summary).map(([k, v]) => `<div class="summary-item"><div class="summary-value">${v}</div><div class="summary-label">${k}</div></div>`).join('')}</div>
<table><tr>${columns.map(c => `<th>${c.label}</th>`).join('')}</tr>
${data.slice(0, 500).map(row => `<tr>${columns.map(c => `<td>${String(row[c.key] ?? '')}</td>`).join('')}</tr>`).join('')}</table>
<div class="footer">${reportTitle} — Generated by Report Center</div>
</body></html>`
          printWindow.document.write(printHtml)
          printWindow.document.close()
          break
        }
      }

      setExported(format)
      setTimeout(() => setExported(null), 3000)
    } catch {
      // Silent
    } finally {
      setExporting(null)
    }
  }

  function downloadFile(content: string, filename: string, mimeType: string) {
    const blob = new Blob([content], { type: mimeType })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  const exportFormats = [
    { id: 'csv', label: 'CSV', icon: FileSpreadsheet, desc: 'Comma-separated values' },
    { id: 'xlsx', label: 'Excel', icon: FileSpreadsheet, desc: 'Spreadsheet (.xlsx)' },
    { id: 'json', label: 'JSON', icon: FileJson, desc: 'Raw data export' },
    { id: 'docx', label: 'Word', icon: FileText, desc: 'Word document (.docx)' },
    { id: 'txt', label: 'Text', icon: FileType, desc: 'Plain text report' },
    { id: 'print', label: 'Print', icon: Printer, desc: 'Print / PDF via browser' },
  ]

  if (data.length === 0) return null

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button className="rounded-xl bg-black text-white hover:bg-black/80 h-10 px-5">
          {exporting ? (
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          ) : exported ? (
            <Check className="mr-2 h-4 w-4" />
          ) : (
            <Download className="mr-2 h-4 w-4" />
          )}
          {exporting ? 'Exporting...' : exported ? 'Exported!' : 'Export'}
          <ChevronDown className="ml-2 h-3.5 w-3.5 opacity-50" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-52">
        {exportFormats.map((fmt) => (
          <DropdownMenuItem
            key={fmt.id}
            onClick={() => handleExport(fmt.id)}
            disabled={exporting !== null}
            className="cursor-pointer"
          >
            <fmt.icon className="mr-2.5 h-4 w-4 text-muted-foreground" />
            <div>
              <p className="text-sm font-medium">{fmt.label}</p>
              <p className="text-xs text-muted-foreground">{fmt.desc}</p>
            </div>
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
