/**
 * Centralized portal URL resolution.
 *
 * Every absolute deep link generated by the frontend (email links,
 * notification links, reset-password URLs, OAuth callbacks, etc.) must go
 * through this helper so production builds never emit `localhost` URLs.
 *
 * Resolution order:
 *   1. NEXT_PUBLIC_APP_URL  — the deployed frontend URL (set in production)
 *   2. VERCEL_PROJECT_PRODUCTION_URL / VERCEL_URL / V0_RUNTIME_URL — Vercel
 *      preview/production origins (kept for parity with lib/auth.ts)
 *   3. http://localhost:3000 — development-only fallback
 */
export function getPortalUrl(): string {
  const envUrl = process.env.NEXT_PUBLIC_APP_URL
  if (envUrl) return envUrl.replace(/\/+$/, '')

  const vercelProduction = process.env.VERCEL_PROJECT_PRODUCTION_URL
  if (vercelProduction) return `https://${vercelProduction}`

  const vercelUrl = process.env.VERCEL_URL
  if (vercelUrl) return `https://${vercelUrl}`

  const v0RuntimeUrl = process.env.V0_RUNTIME_URL
  if (v0RuntimeUrl) return v0RuntimeUrl

  return 'http://localhost:3000'
}

/** Convenience constant — resolved once at module load. */
export const PORTAL_URL = getPortalUrl()
